modLoader = "javafml"
loaderVersion = "[@LOADER_MAJOR@,)"
license = "All-Rights-Reserved"

[[mods]]
modId = "aviator_dream"
version = "${version}"
displayName = "Aviator Dreams"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/aviator-dreams"
authors = "Nax"
description = "An Add-On aimed at adding real life airliners to the game."
logoFile = "icon.png"
itemIcon = "aviator_dream:douglas_dc1"

[[dependencies.aviator_dream]]
modId = "minecraft"
mandatory = true
versionRange = "[@MINECRAFT_VERSION@,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aviator_dream]]
modId = "forge"
mandatory = true
versionRange = "[@LOADER_MAJOR@,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aviator_dream]]
modId = "immersive_aircraft"
mandatory = true
versionRange = "[1.1.0,)"
ordering = "NONE"
side = "BOTH"
